### PR TITLE
[CH-000] - Configuration of routing in backend

### PR DESCRIPTION
**Pull request by cidkhode**
**Tech story (no clubhouse link)**

### CODE REVIEW

**Comment by cidkhode** [comment]
Hey guys, we're gonna need to revisit this right after your midterms, but this is the working solution at this point. Check it out, and let me know what needs to change before tomorrow

**Comment by TheMightyE** [comment]
Never mind, I forgot to run `npm run build` before running the project.

**Comment by cidkhode** [comment]
@Uben thanks for the help! Can you review when you get a chance? I touched up a few things

**Comment by Uben** [comment]
@cidkhode looks good to me!

**Pull request merged**
